#!/usr/bin/env python3
"""Generate the mainnet differential fixture for the Rust port.

Replays, through the upstream bit-exact Python replica, the exact sequence that
FlyBrain v1 executed on BNB Smart Chain
(`0x32D28e97b50f5978eb51d7608492CC7221b01f63`), and dumps:

  * the per-tick observables the Solidity `Differential.t.sol` asserts, and
  * the *complete* final state (every membrane potential, every engram value,
    pending input, heading history, position, heading vector)

so the Rust port can be checked at byte level, not just at spike-count level. A
port that gets the spike counts right but drifts in the sub-threshold potentials
would pass a spike-only test and then diverge on the next tick; this fixture
catches that.

Usage:  python3 scripts/gen_fixture.py
"""

import json
import os
import sys

# scripts/ -> ckb-fly/ -> the workspace that also holds the upstream checkout.
PROJECT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORKSPACE = os.path.dirname(PROJECT)
UPSTREAM = os.path.join(WORKSPACE, "repo")
sys.path.insert(0, os.path.join(UPSTREAM, "sim"))

from flysim import (  # noqa: E402
    CH_CUE,
    CH_SHOCK,
    Circuit,
    FlyBrain,
    keccak256,
    WEDGES,
)

PARAMS_V1 = dict(
    leak=95,
    thresh=1000,
    reset=-500,
    vMin=-4000,
    gains=[190, 114, 5, 108, 7, -297],
    gBias=4,
    noise=35,
    stimGain=157,
    stimTTL=64,
    walkThreshold=100,
    maxSteps=64,
)

INITIAL_ENERGY = 1_000_000
FEED_TOKENS = 10_000  # feed(10_000 ether) with TOKENS_PER_STEP = 1e18


def main():
    circuit = Circuit.load(os.path.join(UPSTREAM, "contracts", "data", "circuit.hex"))
    brain = FlyBrain(circuit, params=PARAMS_V1, energy=INITIAL_ENERGY)

    steps = []

    def record(label, before_total):
        steps.append(
            {
                "label": label,
                "step": brain.step,
                "energy": brain.energy,
                "totalSpikes": brain.totalSpikes,
                "deltaSpikes": brain.totalSpikes - before_total,
                "headX": brain.headX,
                "headY": brain.headY,
                "posX": brain.posX,
                "posY": brain.posY,
            }
        )

    # 1. 64 steps of nothing: the brain is silent with no stimulus and no engram.
    t0 = brain.totalSpikes
    brain.tick(64)
    record("tick(64)", t0)

    # 2. feed(10_000 ether) -> +10_000 steps of life. No tick.
    brain.energy += FEED_TOKENS

    # 3. stimulate(CUE wedge 4, strength 4, steps 32)
    t0 = brain.totalSpikes
    brain.stimulate(CH_CUE, 4, 4)
    brain.tick(32)
    record("stimulate(CUE,4,4,32)", t0)

    # 4. two more ticks of 32
    t0 = brain.totalSpikes
    brain.tick(32)
    record("tick(32)", t0)

    t0 = brain.totalSpikes
    brain.tick(32)
    record("tick(32)", t0)

    # 5. stimulate(SHOCK, strength 4, steps 32)
    t0 = brain.totalSpikes
    brain.stimulate(CH_SHOCK, 0, 4)
    brain.tick(32)
    record("stimulate(SHOCK,0,4,32)", t0)

    # The full state, at full width, for byte-level comparison.
    state = {
        "v": list(brain.v),
        "bias": list(brain.bias),
        "inp": list(brain.inp),
        "hist": list(brain.hist),
        "step": brain.step,
        "energy": brain.energy,
        "totalSpikes": brain.totalSpikes,
        "posX": brain.posX,
        "posY": brain.posY,
        "headX": brain.headX,
        "headY": brain.headY,
        "alive": brain.alive,
        "generation": brain.generation,
    }

    fixture = {
        "_comment": (
            "Generated by scripts/gen_fixture.py from the upstream bit-exact Python "
            "replica. Replays the BSC mainnet v1 trajectory. Do not hand-edit."
        ),
        "circuitSha256": "a1659e1a250cd022cbc4c58fb599f1d47e347b5c5c3e6e454c655f032fb69ae8",
        "circuitKeccak256": "ffbe0e7f28e1f0dd2cfaa01d1d221c502bf41c1fd519ebfe8d9b8203e7cedfc2",
        "params": PARAMS_V1,
        "initialEnergy": INITIAL_ENERGY,
        "feedSteps": FEED_TOKENS,
        "n": circuit.N,
        "s": circuit.S,
        "steps": steps,
        "finalState": state,
    }

    out_dir = os.path.join(PROJECT, "crates", "flycore", "tests", "fixtures")
    os.makedirs(out_dir, exist_ok=True)
    out = os.path.join(out_dir, "mainnet_v1.json")
    with open(out, "w") as f:
        json.dump(fixture, f, indent=1, sort_keys=True)
        f.write("\n")

    print(f"wrote {out}")
    print(f"  circuit  N={circuit.N} S={circuit.S}")
    for s in steps:
        print(
            f"  {s['label']:<28} step={s['step']:>4} spikes=+{s['deltaSpikes']:<4}"
            f" total={s['totalSpikes']:<4} head=({s['headX']},{s['headY']})"
            f" pos=({s['posX']},{s['posY']}) energy={s['energy']}"
        )
    # Sanity: the fixture must be self-consistent with the Solidity assertions.
    assert steps[0]["deltaSpikes"] == 0
    assert steps[1]["totalSpikes"] == 279
    assert steps[2]["totalSpikes"] == 533
    assert steps[3]["totalSpikes"] == 533
    assert steps[4]["totalSpikes"] == 816
    assert steps[4]["energy"] == 1_009_808
    print("  Solidity Differential.t.sol assertions: OK")


if __name__ == "__main__":
    main()
