//! Differential test: does the Rust port reproduce BSC mainnet, bit for bit?
//!
//! `fixtures/mainnet_v1.json` is generated by `scripts/gen_fixture.py`, which drives the
//! upstream bit-exact Python replica (`repo/sim/flysim.py`) through the exact sequence
//! that FlyBrain v1 (`0x32D28e97b50f5978eb51d7608492CC7221b01f63`) executed on BNB Smart
//! Chain. The same numbers are asserted by the upstream `Differential.t.sol`.
//!
//! The fixture deliberately records **every** membrane potential, engram value and
//! pending-input accumulator, not just the spike counts. A port can match spike counts
//! while drifting in the sub-threshold regime, and the drift only becomes visible one
//! tick later — which is exactly the kind of bug that would ship, look fine, and then
//! produce a different fly than BSC's.

use flycircuit::embedded;
use flycore::args::ScriptArgs;
use flycore::economics::Economics;
use flycore::params::Params;
use flycore::sim::{CH_CUE, CH_NONE, CH_SHOCK, Sim};
use flycore::state::{StateError, state_len};
use serde_json::Value;

const FIXTURE: &str = include_str!("fixtures/mainnet_v1.json");

/// Circuit identity: the byte string the BSC contract reports from `circuitHash()`.
const CIRCUIT_KECCAK: &str = "ffbe0e7f28e1f0dd2cfaa01d1d221c502bf41c1fd519ebfe8d9b8203e7cedfc2";

fn fixture() -> Value {
    serde_json::from_str(FIXTURE).expect("fixture is valid JSON")
}

fn i64_list(v: &Value, key: &str) -> Vec<i64> {
    v[key]
        .as_array()
        .unwrap_or_else(|| panic!("{key} is an array"))
        .iter()
        .map(|x| x.as_i64().unwrap_or_else(|| panic!("{key} holds integers")))
        .collect()
}

fn field<'a>(v: &'a Value, key: &str) -> &'a Value {
    v.get(key).unwrap_or_else(|| panic!("missing field {key}"))
}

/// Run the fixture's action sequence, calling `on_tick` after each observable step.
///
/// The sequence is the one in `Differential.t.sol`:
/// `tick(64)`, `feed(10_000 ether)`, `stimulate(CUE,4,4,32)`, `tick(32)`, `tick(32)`,
/// `stimulate(SHOCK,0,4,32)`.
fn replay(fx: &Value, mut on_tick: impl FnMut(usize, &Sim)) -> Sim<'static> {
    let c = embedded();
    let p = Params::V1_DEPLOYED;
    let initial = field(fx, "initialEnergy").as_u64().unwrap();
    let feed = field(fx, "feedSteps").as_u64().unwrap();

    let mut sim = Sim::genesis(c, p, initial, 0);

    // 1. 64 silent steps.
    sim.tick(64).expect("genesis tick");
    on_tick(0, &sim);

    // 2. feed(10_000 ether). The 64 steps above have already been paid for.
    assert!(sim.feed(feed), "feed on a live fly must succeed");
    assert_eq!(sim.energy, initial + feed - 64);

    // 3. stimulate(CUE wedge 4, strength 4, then 32 steps)
    assert!(sim.stimulate(CH_CUE, 4, 4));
    sim.tick(32).expect("cue tick");
    on_tick(1, &sim);

    // 4. two more ticks
    sim.tick(32).expect("tick 2");
    on_tick(2, &sim);
    sim.tick(32).expect("tick 3");
    on_tick(3, &sim);

    // 5. stimulate(SHOCK, strength 4, then 32 steps)
    assert!(sim.stimulate(CH_SHOCK, 0, 4));
    sim.tick(32).expect("shock tick");
    on_tick(4, &sim);

    sim
}

#[test]
fn circuit_identity_is_preserved_from_bsc() {
    let c = embedded();
    let h = flycore::keccak::keccak256(c.table());
    let hex: String = h.iter().map(|b| format!("{b:02x}")).collect();
    assert_eq!(
        hex, CIRCUIT_KECCAK,
        "the CKB port must run the identical connectome bytes"
    );
    assert_eq!(hex, fixture()["circuitKeccak256"].as_str().unwrap());
}

#[test]
fn replay_mainnet_v1_matches_solidity_assertions() {
    let fx = fixture();
    let expected = field(&fx, "steps").as_array().unwrap().clone();
    assert_eq!(expected.len(), 5, "five observable steps");

    let mut seen = 0usize;
    let sim = replay(&fx, |k, sim| {
        let e = &expected[k];
        let label = e["label"].as_str().unwrap();
        let want = |key: &str| e[key].as_i64().unwrap();

        assert_eq!(sim.step as i64, want("step"), "{label}: step");
        assert_eq!(sim.energy as i64, want("energy"), "{label}: energy");
        assert_eq!(
            sim.total_spikes as i64,
            want("totalSpikes"),
            "{label}: cumulative spikes"
        );
        assert_eq!(sim.head_x as i64, want("headX"), "{label}: headX");
        assert_eq!(sim.head_y as i64, want("headY"), "{label}: headY");
        assert_eq!(sim.pos_x, want("posX"), "{label}: posX");
        assert_eq!(sim.pos_y, want("posY"), "{label}: posY");
        seen += 1;
    });
    assert_eq!(seen, 5);

    // The four assertions that `Differential.t.sol` makes by hand.
    assert_eq!(sim.total_spikes, 816);
    assert_eq!(sim.energy, 1_009_808);

    // After the shock the bump collapses: the compass vector is exactly zero.
    assert_eq!((sim.head_x, sim.head_y), (0, 0));
}

#[test]
fn replay_mainnet_v1_matches_every_neuron() {
    let fx = fixture();
    let final_state = field(&fx, "finalState");

    let sim = replay(&fx, |_, _| {});

    let n = field(&fx, "n").as_u64().unwrap() as usize;
    assert_eq!(n, 155);
    assert_eq!(sim.circuit.n(), n);

    let want_v = i64_list(final_state, "v");
    let want_bias = i64_list(final_state, "bias");
    let want_inp = i64_list(final_state, "inp");
    let want_hist = i64_list(final_state, "hist");

    for i in 0..n {
        assert_eq!(sim.v[i], want_v[i], "v[{i}] diverged");
        assert_eq!(sim.bias[i] as i64, want_bias[i], "bias[{i}] diverged");
        assert_eq!(sim.inp[i], want_inp[i], "inp[{i}] diverged");
    }
    for (w, (&got, &want)) in sim.hist.iter().zip(want_hist.iter()).enumerate() {
        assert_eq!(got as i64, want, "hist[{w}] diverged");
    }

    assert_eq!(sim.step, field(final_state, "step").as_u64().unwrap());
    assert_eq!(sim.energy, field(final_state, "energy").as_u64().unwrap());
    assert_eq!(
        sim.total_spikes,
        field(final_state, "totalSpikes").as_u64().unwrap()
    );
    assert_eq!(sim.pos_x, field(final_state, "posX").as_i64().unwrap());
    assert_eq!(sim.pos_y, field(final_state, "posY").as_i64().unwrap());
    assert_eq!(
        sim.head_x as i64,
        field(final_state, "headX").as_i64().unwrap()
    );
    assert_eq!(
        sim.head_y as i64,
        field(final_state, "headY").as_i64().unwrap()
    );
    assert_eq!(sim.alive, field(final_state, "alive").as_bool().unwrap());
    assert_eq!(
        sim.generation,
        field(final_state, "generation").as_u64().unwrap() as u32
    );

    // The engram must have moved: an all-zero bias would mean plasticity never ran,
    // and the per-neuron assertions above would then be vacuous.
    assert!(
        sim.bias.iter().any(|&b| b != 0),
        "engram is all zeros — plasticity did not run"
    );
}

#[test]
fn the_bump_collapses_under_shock_and_recovers_under_cue() {
    // The behavioural claim behind the whole circuit: a landmark cue builds a heading,
    // and a noxious stimulus flattens it. Verified on the real trajectory.
    let fx = fixture();
    let mut heading_with_cue = None;
    let sim = replay(&fx, |k, sim| {
        if k == 1 {
            heading_with_cue = Some((sim.head_x, sim.head_y));
        }
    });
    let (hx, hy) = heading_with_cue.unwrap();
    let mag = ((hx as f64).powi(2) + (hy as f64).powi(2)).sqrt();
    assert!(mag > 10_000.0, "cue should build a strong bump, got {mag}");

    let after_shock = ((sim.head_x as f64).powi(2) + (sim.head_y as f64).powi(2)).sqrt();
    assert_eq!(after_shock, 0.0, "shock should collapse the bump");
}

#[test]
fn replay_is_deterministic() {
    // No block data, no clock, no hash of the transaction: the only inputs are the step
    // number and the circuit. Two runs in the same process must agree byte for byte.
    let fx = fixture();
    let a = replay(&fx, |_, _| {});
    let b = replay(&fx, |_, _| {});
    assert_eq!(a.state_hash(), b.state_hash());

    let mut buf_a = vec![0u8; state_len(155)];
    let mut buf_b = vec![0u8; state_len(155)];
    a.encode(&mut buf_a).unwrap();
    b.encode(&mut buf_b).unwrap();
    assert_eq!(buf_a, buf_b);
}

#[test]
fn state_round_trips_at_every_tick() {
    // A tick boundary is where the state is written to the cell. If encode/decode is
    // lossy, the chain and an off-chain replica drift apart one tick at a time.
    let fx = fixture();
    let mut checks = 0;
    replay(&fx, |_, sim| {
        let mut buf = vec![0u8; state_len(155)];
        sim.encode(&mut buf).unwrap();
        let back = Sim::decode(embedded(), Params::V1_DEPLOYED, &buf).unwrap();
        assert_eq!(back.state_hash(), sim.state_hash());
        assert_eq!(back.step, sim.step);
        assert_eq!(back.energy, sim.energy);
        for i in 0..155 {
            assert_eq!(back.v[i], sim.v[i].clamp(i16::MIN as i64, i16::MAX as i64));
            assert_eq!(back.bias[i], sim.bias[i]);
            // v1 does not persist pending input, so the cell must read back zero even
            // though the in-flight accumulator is non-empty.
            assert_eq!(back.inp[i], 0, "v1 must not persist pending input");
        }
        checks += 1;
    });
    assert_eq!(checks, 5);
}

#[test]
fn tick_rejects_arguments_that_would_revert_upstream() {
    let fx = fixture();
    let c = embedded();
    let initial = field(&fx, "initialEnergy").as_u64().unwrap();
    let mut sim = Sim::genesis(c, Params::V1_DEPLOYED, initial, 0);

    assert!(sim.tick(0).is_none(), "steps == 0 reverts");
    assert!(sim.tick(65).is_none(), "steps > max_steps reverts");
    assert!(sim.tick(64).is_some(), "64 steps is the maximum");

    // Stimulus argument validation, mirroring `_stimulate`'s reverts.
    assert!(!sim.stimulate(CH_NONE, 0, 1), "channel 0 is CH_NONE");
    assert!(!sim.stimulate(5, 0, 1), "channel 5 does not exist");
    assert!(!sim.stimulate(CH_CUE, 0, 0), "strength 0");
    assert!(!sim.stimulate(CH_CUE, 16, 1), "wedge 16 is out of range");
    assert!(sim.stimulate(CH_CUE, 15, 1));
    assert!(
        sim.stimulate(CH_SHOCK, 0, 255),
        "param is ignored for SHOCK"
    );
}

#[test]
fn a_tick_that_exhausts_energy_kills_the_fly() {
    let c = embedded();
    // 10 steps of energy, then ask for 64: only 10 run, and the fly dies.
    let mut sim = Sim::genesis(c, Params::V1_DEPLOYED, 10, 0);
    let r = sim.tick(64).unwrap();
    assert_eq!(r.steps, 10, "only as many steps as energy allows");
    assert_eq!(r.energy, 0);
    assert!(r.died);
    assert!(!sim.alive);
    assert_eq!(sim.step, 10);

    // A dead fly cannot be ticked, stimulated, or fed.
    assert!(sim.tick(1).is_none());
    assert!(!sim.stimulate(CH_CUE, 0, 1));
    assert!(
        !sim.feed(1_000),
        "upstream `_feed` lacks an `alive` check, so feeding a corpse burns tokens for \
         nothing; the port refuses instead"
    );
    assert_eq!(sim.energy, 0);
}

#[test]
fn resurrection_requires_energy() {
    let c = embedded();
    let mut sim = Sim::genesis(c, Params::V1_DEPLOYED, 1, 0);
    sim.tick(1).unwrap();
    assert!(!sim.alive);

    assert!(sim.can_resurrect());
    assert!(
        !sim.resurrect(0, 100),
        "upstream `_resurrect(0)` burns the full price and then dies again on the next \
         tick; the port refuses zero energy"
    );
    assert!(!sim.alive, "a refused resurrection must not revive the fly");

    assert!(sim.resurrect(5, 100));
    assert!(sim.alive);
    assert_eq!(sim.generation, 1);
    assert_eq!(sim.energy, 5);
    assert_eq!(sim.born_block, 100);
    assert_eq!(sim.life_steps, 0);
    assert_eq!(sim.life_spikes, 0);
    assert_eq!((sim.pos_x, sim.pos_y), (0, 0));

    // Resurrection is idempotent-hostile: a live fly cannot be resurrected again.
    assert!(!sim.can_resurrect());
    assert!(!sim.resurrect(5, 200));
    assert_eq!(sim.generation, 1);
}

#[test]
fn persistence_of_pending_input_differs_between_v1_and_v2() {
    // This is the single behavioural difference between the two deployed parameter sets,
    // and it is easy to get wrong because it only shows up at a tick boundary: v1 throws
    // away the synaptic input that was in flight, v2 keeps it.
    //
    // Both runs use identical dynamics, so any divergence is attributable to
    // `persist_input` alone.
    let c = embedded();
    let mut v1 = Params::V1_DEPLOYED;
    v1.persist_input = false;
    let mut v2 = Params::V1_DEPLOYED;
    v2.persist_input = true;

    let run = |params: Params| {
        let mut sim = Sim::genesis(c, params, 1_000_000, 0);
        sim.stimulate(CH_CUE, 4, 4);
        // Small ticks, so the tick boundary is crossed often and the carried input has
        // many chances to matter.
        for _ in 0..8 {
            sim.tick(4).unwrap();
        }
        let mut buf = vec![0u8; state_len(155)];
        sim.encode(&mut buf).unwrap();
        let in_flight = sim.inp.iter().filter(|&&x| x != 0).count();
        let region = &buf[flycore::state::off_inp(155)..];
        let stored = (0..155)
            .filter(|&i| region[4 * i..4 * i + 4].iter().any(|&b| b != 0))
            .count();
        (sim.total_spikes, sim.head_x, sim.head_y, in_flight, stored)
    };

    let (spikes_v1, hx_v1, hy_v1, in_flight_v1, stored_v1) = run(v1);
    let (spikes_v2, hx_v2, hy_v2, in_flight_v2, stored_v2) = run(v2);

    assert!(
        in_flight_v1 > 0,
        "after a tick both variants hold input destined for the next step"
    );
    assert_eq!(stored_v1, 0, "v1 must never write the input region");
    assert_eq!(
        stored_v2, in_flight_v2,
        "v2 must write exactly the input that is in flight"
    );
    assert!(
        (spikes_v1, hx_v1, hy_v1) != (spikes_v2, hx_v2, hy_v2),
        "dropping versus keeping pending input must change the fly: \
         v1 gave {spikes_v1} spikes / ({hx_v1},{hy_v1}), v2 gave {spikes_v2} / ({hx_v2},{hy_v2})"
    );
}

#[test]
fn args_pin_the_circuit_the_parameters_and_the_economics() {
    let c = embedded();
    let hash = flycore::keccak::keccak256(c.table());
    let econ = Economics::TESTNET;
    let args = ScriptArgs::new([0x11; 8], Params::V1_DEPLOYED, hash, econ);
    let bytes = args.to_bytes();

    assert_eq!(bytes.len(), 97);
    assert_eq!(ScriptArgs::from_bytes(&bytes), Some(args));

    // Same code hash + different args = a different type script on CKB, which is what
    // stops anyone from re-pointing a live fly at a different connectome, changing its
    // dynamics, or repricing its life.
    assert_ne!(
        bytes,
        ScriptArgs::new([0x11; 8], Params::V2, hash, econ).to_bytes()
    );

    let mut different_circuit = hash;
    different_circuit[0] ^= 1;
    assert_ne!(
        bytes,
        ScriptArgs::new([0x11; 8], Params::V1_DEPLOYED, different_circuit, econ).to_bytes()
    );

    assert_ne!(
        bytes,
        ScriptArgs::new([0x11; 8], Params::V1_DEPLOYED, hash, Economics::FREE).to_bytes()
    );

    // And the one that is easiest to leave out: two flies with the same genome are still two
    // organisms. Without the instance field they share a type script, so "find the cell
    // wearing the fly's type script" finds an arbitrary one of them.
    assert_ne!(
        bytes,
        ScriptArgs::new([0x22; 8], Params::V1_DEPLOYED, hash, econ).to_bytes(),
        "the instance must be part of the identity",
    );
}

#[test]
fn malformed_cells_are_rejected() {
    let c = embedded();
    let sim = Sim::genesis(c, Params::V1_DEPLOYED, 1_000, 0);
    let mut buf = vec![0u8; state_len(155)];
    sim.encode(&mut buf).unwrap();

    assert!(Sim::decode(c, Params::V1_DEPLOYED, &buf).is_ok());

    // A cell whose `alive` byte is neither 0 nor 1 must not be accepted, or the
    // validator's `alive` semantics would be ambiguous.
    let mut bad = buf.clone();
    bad[2] = 2;
    assert_eq!(
        Sim::decode(c, Params::V1_DEPLOYED, &bad).unwrap_err(),
        StateError::BadField("alive")
    );

    // Padding is part of the encoding: a non-canonical cell would let two different
    // byte strings claim the same state.
    let mut bad = buf.clone();
    bad[20] = 1;
    assert_eq!(
        Sim::decode(c, Params::V1_DEPLOYED, &bad).unwrap_err(),
        StateError::BadField("pad")
    );

    // An unknown stimulus channel must not be silently accepted.
    let mut bad = buf;
    bad[3] = 9;
    assert_eq!(
        Sim::decode(c, Params::V1_DEPLOYED, &bad).unwrap_err(),
        StateError::BadField("stim_channel")
    );
}
